# Site settings
baseurl = "https://example.org/"
languageCode = "en-us"
title = "Douglas Delefrati"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Douglas Delefrati"
    deion = "Software Engineer, Web Developer, Programmer"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "douglasdelefrati@gmail.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = ""


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Douglas Delefrati"
        subtitle = "Developer"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Portfolio"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "I'm a Computer Science student in State University of Maringá, and I will graduate at the end of 2021 (hopefully). I was a member of PET Informática UEM for almost two years, in that time I helped organize two editions of SECOMP, an regional event of technology. I presented courses for students about programming languages, like C, Python and Java. Also, I actively participated in the development of the group's official website, as well as an event management system." 
        right = "In early 2020, I started working at eureka labs as a web developer. Since then, I helped to develop a marketplace platform, in which I had contact with Node and React frameworks. At the moment I have more experience as a back end developer, but I am studying React frameworks and DevOps practices"

        [params.about.button]
            text = "Download Resume"
            link = "#"
            icon = "download"


    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Made by Douglas Delefrati. Powered by [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["Brazil", "Maringá, PR"]

        [params.footer.social]
            title = "Where to find me"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/deelefrati"

            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link=  "//www.linkedin.com/in/douglas-delefrati-388b9815a/"


      
