# Site settings
baseURL = "https://delefrati.dev"
languageCode = "en-us"
title = "Douglas Delefrati"
theme = "archie"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="dark" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "COMO TIRA LETRA GRAMDE"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/deelefrati/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/douglas-delefrati-388b9815a/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

